version: 2.1

commands:
  test-nodejs:
    steps:
      - run:
          name: Versions
          command: npm version
      - checkout
      - restore_cache:
          keys:
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ arch }}-npm-cache-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ arch }}-npm-cache-master-{{ .Environment.CIRCLE_JOB }}
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Test
          command: npm test
      - run:
          name: Test examples
          command: |
            cd examples/build-and-serve
            npm i
            npm run build:ci
      - run:
          name: Test in the oldest Google Closure Tools
          command: |
            npm i --no-save google-closure-compiler@20180910 google-closure-deps@20190325
            npm run unit
      - run:
          name: Test examples in the oldest Google Closure Tools
          command: |
            cd examples/build-and-serve
            npm run build:ci
      - run:
          name: Report coverage to codecov
          command: |
            if [ "$CIRCLE_JOB" = 'node-v12' ]; then
              npx codecov
            else
              echo "Skip reporting coverage to codecov"
            fi
      - save_cache:
          key: v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ arch }}-npm-cache-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

jobs:
  node-v10:
    docker:
      - image: node:10
    steps:
      - test-nodejs
  node-v12:
    docker:
      - image: node:12
    steps:
      - test-nodejs
  node-v13:
    docker:
      - image: node:13
    steps:
      - test-nodejs

workflows:
  node-multi-build:
    jobs:
      - node-v10
      - node-v12
      - node-v13
